return {
	Title = "界青快剑-连击版",
	Source = 0,
	FileId = 3752682766,
	Version = "0.0.0.1",
	GameVersion = "1.0.36-gm",
	Author = "Duma",
	Description = "1.无限连击  20%保底几率\n2.初始几率 60%  每次连击-15%\n3.将福缘与初始几率关联，  初始几率= 60% + 福缘/2  \n4.连击时，释放进度，随连击数增长，每多一连，增加10%，最高至99%\v",
	TagList = {
		[1] = "Compatible Mods",
		[2] = "Modifications",
	},
	Visibility = 0,
	DefaultSettings = { },
	UpdateLogList = {
		[1] = {
			Timestamp = 1782556985,
		},
	},
	ChangeConfig = false,
	HasArchive = false,
	NeedRestartWhenSettingChanged = true,
	BackendPlugins = {
		[1] = "JQKJ.Combo.Backend.dll",
	},
	FrontendPlugins = {
		[1] = "JQKJ.Combo.Frontend.dll",
	},
	Cover = "快剑.png",
	WorkshopCover = "快剑.png",
}
